# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

os: osx
osx_image: xcode10.1
language: objective-c

cache: cocoapods
podfile: Example/Podfile

before_install:
- brew update
- gem install cocoapods -v 1.6.0 # Since Travis is not always on latest version
- pod repo update
- pod install --project-directory=Example
- pod install --project-directory=TensorFlowExample
- pod install --project-directory=SwiftExample
- pod install --project-directory=DeployExample

script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/TensorIO.xcworkspace -scheme TensorIO-Example -sdk iphonesimulator12.1 -arch x86_64 ONLY_ACTIVE_ARCH=NO | xcpretty
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace TensorFlowExample/TensorFlowExample.xcworkspace -scheme TensorFlowExample -sdk iphonesimulator12.1 -arch x86_64 ONLY_ACTIVE_ARCH=NO | xcpretty
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace SwiftExample/SwiftExample.xcworkspace -scheme SwiftExample -sdk iphonesimulator12.1 -arch x86_64 ONLY_ACTIVE_ARCH=NO | xcpretty
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace DeployExample/DeployExample.xcworkspace -scheme DeployExample -sdk iphonesimulator12.1 -arch x86_64 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint --skip-import-validation --allow-warnings

before_deploy:
- gem install jazzy # To generate documentation
- jazzy

deploy:
  provider: s3
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  bucket: "tensorio.net"
  skip_cleanup: true
  local_dir: docs
  region: "us-west-1"
  on:
    branch: master